// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWJtV3i6PeYbqmdlFacpLsQknxCABf95E',
    appId: '1:824176469521:web:553e02c24a7c6ab676b3b0',
    messagingSenderId: '824176469521',
    projectId: 'npkdtech',
    authDomain: 'npkdtech.firebaseapp.com',
    storageBucket: 'npkdtech.firebasestorage.app',
    measurementId: 'G-18TCEFCMF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqdg4O7v1jpJntqB7QC5tV4om1pBzqngA',
    appId: '1:824176469521:android:0ddf846db457ef6576b3b0',
    messagingSenderId: '824176469521',
    projectId: 'npkdtech',
    storageBucket: 'npkdtech.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqt6l1A8JofIDD8FB7qbrP4ScQ6hHVQXY',
    appId: '1:824176469521:ios:fb1c78ca0c7e4a5f76b3b0',
    messagingSenderId: '824176469521',
    projectId: 'npkdtech',
    storageBucket: 'npkdtech.firebasestorage.app',
    iosBundleId: 'com.example.npkApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqt6l1A8JofIDD8FB7qbrP4ScQ6hHVQXY',
    appId: '1:824176469521:ios:fb1c78ca0c7e4a5f76b3b0',
    messagingSenderId: '824176469521',
    projectId: 'npkdtech',
    storageBucket: 'npkdtech.firebasestorage.app',
    iosBundleId: 'com.example.npkApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWJtV3i6PeYbqmdlFacpLsQknxCABf95E',
    appId: '1:824176469521:web:b847686f2963adee76b3b0',
    messagingSenderId: '824176469521',
    projectId: 'npkdtech',
    authDomain: 'npkdtech.firebaseapp.com',
    storageBucket: 'npkdtech.firebasestorage.app',
    measurementId: 'G-EDZ0S5T2TJ',
  );
}
